name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: renovate/renovate:39.137

    steps:
      - uses: actions/checkout@v4

      - name: Renovate
        run: renovate
